### ISSUE TITLE
packages.yaml: perl: should CPAN variant be disabled?

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/spack-config#23]
The current Perl `spec` is:
```
  perl:
    externals:
    - spec: perl@5.26.3~cpanm+shared+threads
      prefix: /usr
    buildable: false
```

It originates from:
```
commit 8b156bf85bdf96398eff98589cd510d8e64e6930
Author: Aidan Heerdegen <aidan.heerdegen@anu.edu.au>
Date:   Mon Oct 31 15:40:33 2022 +1100

    Initial commit of packages.yaml config file
```

I found that Spack defaults to:
```
0.19.x: perl@5.35.0+cpanm+shared+threads
0.20.3: perl@5.36.0+cpanm+open+shared+threads
0.21.1: perl@5.38.0+cpanm+opcode+open+shared+threads
```
openmpi's SPD depends on default perl:
```
    depends_on("perl", type="build")
```
We should confirm whether there is a good reason to use a `spec` with `~cpanm` (i.e. `cpanm` disabled).
